owner: GitLost-dotcom
repo: cooperandhunter-status

sites:
  - name: Cooper&Hunter Web
    url: https://cooperandhunter.sk
  - name: Django Backend (API)
    url: https://cooperandhunter.sk/api/b2b/settings/global/
  - name: Umami Analytics
    url: https://cooperandhunter.sk:8443/api/heartbeat
  - name: n8n AI Server
    url: http://195.210.28.32:5678/healthz

assignees:
  - GitLost-dotcom

status-website:
  baseUrl: /cooperandhunter-status
  logoUrl: https://www.cooperandhunter.sk/COOL%20logo.png
  name: Cooper&Hunter Status
  introTitle: "**Stav systémov Cooper&Hunter Slovensko**"
  introMessage: Real-time monitoring dostupnosti nášho e-shopu, B2B portálu a interných systémov.
  navbar:
    - title: Hlavný web
      href: https://cooperandhunter.sk
    - title: GitHub
      href: $REPO

i18n:
  activeIncidents: Aktívne výpadky
  allSystemsOperational: Všetky systémy sú plne funkčné
  incidentReport: "Hlásenie o výpadku #$NUMBER"
  activeIncidentSummary: Voľný čas $DATE, nahlásených $POSTS problémov.
  down: Offline
  up: Funkčné
  degraded: Čiastočný výpadok
